### ISSUE TITLE
Alamat Database

### ISSUE THREAD

**Issue by mwafa** [putupradnya/JuniorProgrammer#1]
https://github.com/putupradnya/JuniorProgrammer/blob/4c616dbf33ffb4f1e7473b0ebed9371424e44bd9/crud.py#L29

Lebih baik ini dibikin di atas pakai relative path.
misal pakai library os

```python
import os
DB_DIR= os.path.join(os.path.dirname(os.path.realpath(__file__)),"dbtoko.sqlite")
print(DB_DIR)
```

**Comment by putupradnya** [comment]
Nicee, nanti diubah supaya lebih dinamis
